#! /bin/bash

set -e

echo "setup the curent environment"
CURRENT_DIRECTORY="$( dirname "${BASH_SOURCE[0]}" )"
cd "${CURRENT_DIRECTORY}"
echo "current directory: $( pwd )"
echo "setup development environment for zumba-zes inference"
YOLOv8_SRC_INFERENCE_DIR="$( cd .. && pwd )"
echo "dev directory set to: ${YOLOv8_SRC_INFERENCE_DIR}"
echo "remove old virtual environment"
rm -rf "${YOLOv8_SRC_INFERENCE_DIR}/.venv"
echo "create new virtual environment"
python3.9 -m venv "${YOLOv8_SRC_INFERENCE_DIR}/.venv"
echo "activate virtual environment"
source "${YOLOv8_SRC_INFERENCE_DIR}/.venv/bin/activate"
echo "installing dependencies ..."
(cd "${YOLOv8_SRC_INFERENCE_DIR}" && pip install --upgrade pip && pip install -r requirements.txt)